server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://mobylab-app-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0

vars:
  security:
    enable: true

token:
  ttl: 3600000
  secret: bookswap-super-secret-key-must-be-at-least-64-characters-long!!!!

admin:
  username: admin
  email: admin@admin.com
  password: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true