/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOfferFromContextDto
 */
export interface CreateOfferFromContextDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOfferFromContextDto
     */
    receiverEmail?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOfferFromContextDto
     */
    offeredBookTitles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOfferFromContextDto
     */
    requestedBookTitles?: Array<string>;
}

/**
 * Check if a given object implements the CreateOfferFromContextDto interface.
 */
export function instanceOfCreateOfferFromContextDto(value: object): value is CreateOfferFromContextDto {
    return true;
}

export function CreateOfferFromContextDtoFromJSON(json: any): CreateOfferFromContextDto {
    return CreateOfferFromContextDtoFromJSONTyped(json, false);
}

export function CreateOfferFromContextDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOfferFromContextDto {
    if (json == null) {
        return json;
    }
    return {
        
        'receiverEmail': json['receiverEmail'] == null ? undefined : json['receiverEmail'],
        'offeredBookTitles': json['offeredBookTitles'] == null ? undefined : json['offeredBookTitles'],
        'requestedBookTitles': json['requestedBookTitles'] == null ? undefined : json['requestedBookTitles'],
    };
}

export function CreateOfferFromContextDtoToJSON(json: any): CreateOfferFromContextDto {
    return CreateOfferFromContextDtoToJSONTyped(json, false);
}

export function CreateOfferFromContextDtoToJSONTyped(value?: CreateOfferFromContextDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receiverEmail': value['receiverEmail'],
        'offeredBookTitles': value['offeredBookTitles'],
        'requestedBookTitles': value['requestedBookTitles'],
    };
}

