spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://mobylab-app-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 80579ee70d4a4f
    password: 45414c44802ca4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

vars:
  security:
    enable: true

server:
  port: 8090
  server.address: 0.0.0.0

token:
  ttl: 3600000
  secret: "https://www.youtube.com/watch?v=VBUMYOYJISc"

admin:
  username: admin
  email: admin@admin.com
  password: admin

