/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Book,
  BookDto,
  BookWithOwnerDto,
} from '../models/index';
import {
    BookFromJSON,
    BookToJSON,
    BookDtoFromJSON,
    BookDtoToJSON,
    BookWithOwnerDtoFromJSON,
    BookWithOwnerDtoToJSON,
} from '../models/index';

export interface AddBookRequest {
    bookDto: BookDto;
}

export interface DeleteBookByTitleRequest {
    title: string;
}

export interface EditBookRequest {
    id: string;
    bookDto: BookDto;
}

export interface GetBooksByAuthorRequest {
    author: string;
}

/**
 * 
 */
export class BookControllerApi extends runtime.BaseAPI {

    /**
     */
    async addBookRaw(requestParameters: AddBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        if (requestParameters['bookDto'] == null) {
            throw new runtime.RequiredError(
                'bookDto',
                'Required parameter "bookDto" was null or undefined when calling addBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/addBook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookDtoToJSON(requestParameters['bookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     */
    async addBook(requestParameters: AddBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.addBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteBookByTitleRaw(requestParameters: DeleteBookByTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling deleteBookByTitle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/deleteByTitle`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteBookByTitle(requestParameters: DeleteBookByTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBookByTitleRaw(requestParameters, initOverrides);
    }

    /**
     */
    async editBookRaw(requestParameters: EditBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling editBook().'
            );
        }

        if (requestParameters['bookDto'] == null) {
            throw new runtime.RequiredError(
                'bookDto',
                'Required parameter "bookDto" was null or undefined when calling editBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/editBook/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BookDtoToJSON(requestParameters['bookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     */
    async editBook(requestParameters: EditBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.editBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllBooksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookWithOwnerDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookWithOwnerDtoFromJSON));
    }

    /**
     */
    async getAllBooks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookWithOwnerDto>> {
        const response = await this.getAllBooksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getBooksByAuthorRaw(requestParameters: GetBooksByAuthorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookWithOwnerDto>>> {
        if (requestParameters['author'] == null) {
            throw new runtime.RequiredError(
                'author',
                'Required parameter "author" was null or undefined when calling getBooksByAuthor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['author'] != null) {
            queryParameters['author'] = requestParameters['author'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/getByAuthor`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookWithOwnerDtoFromJSON));
    }

    /**
     */
    async getBooksByAuthor(requestParameters: GetBooksByAuthorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookWithOwnerDto>> {
        const response = await this.getBooksByAuthorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
