/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOfferFromContextDto,
  OfferDto,
} from '../models/index';
import {
    CreateOfferFromContextDtoFromJSON,
    CreateOfferFromContextDtoToJSON,
    OfferDtoFromJSON,
    OfferDtoToJSON,
} from '../models/index';

export interface CreateOfferFromAuthenticatedUserRequest {
    createOfferFromContextDto: CreateOfferFromContextDto;
}

export interface GetOffersReceivedRequest {
    userId: string;
}

export interface RespondToOfferRequest {
    id: string;
    status: string;
}

/**
 * 
 */
export class OfferControllerApi extends runtime.BaseAPI {

    /**
     */
    async createOfferFromAuthenticatedUserRaw(requestParameters: CreateOfferFromAuthenticatedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfferDto>> {
        if (requestParameters['createOfferFromContextDto'] == null) {
            throw new runtime.RequiredError(
                'createOfferFromContextDto',
                'Required parameter "createOfferFromContextDto" was null or undefined when calling createOfferFromAuthenticatedUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/me`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOfferFromContextDtoToJSON(requestParameters['createOfferFromContextDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferDtoFromJSON(jsonValue));
    }

    /**
     */
    async createOfferFromAuthenticatedUser(requestParameters: CreateOfferFromAuthenticatedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfferDto> {
        const response = await this.createOfferFromAuthenticatedUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllUserOffersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OfferDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OfferDtoFromJSON));
    }

    /**
     */
    async getAllUserOffers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OfferDto>> {
        const response = await this.getAllUserOffersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getOffersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OfferDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/offers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OfferDtoFromJSON));
    }

    /**
     */
    async getOffers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OfferDto>> {
        const response = await this.getOffersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getOffersReceivedRaw(requestParameters: GetOffersReceivedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OfferDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getOffersReceived().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/received`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OfferDtoFromJSON));
    }

    /**
     */
    async getOffersReceived(requestParameters: GetOffersReceivedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OfferDto>> {
        const response = await this.getOffersReceivedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOffersReceivedByAuthenticatedUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OfferDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/received/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OfferDtoFromJSON));
    }

    /**
     */
    async getOffersReceivedByAuthenticatedUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OfferDto>> {
        const response = await this.getOffersReceivedByAuthenticatedUserRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async respondToOfferRaw(requestParameters: RespondToOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfferDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling respondToOffer().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling respondToOffer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/{id}/status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferDtoFromJSON(jsonValue));
    }

    /**
     */
    async respondToOffer(requestParameters: RespondToOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfferDto> {
        const response = await this.respondToOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
